# Generated by Django 6.1.1 on 2026-09-15 05:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ownership_type', models.CharField(choices=[('assigned', 'Assigned'), ('claimable', 'Claimable')], max_length=20)),
                ('recurrence_rule', models.CharField(blank=True, help_text="e.g. 'daily', 'weekly:tuesday'. Blank means one-off.", max_length=255)),
                ('verification_mode', models.CharField(choices=[('instant', 'Instant'), ('approval', 'Approval')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_chore_definitions', to='chores.familymember')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_definitions', to='chores.household')),
            ],
        ),
    ]
