# Generated by Django 6.1.1 on 2026-09-15 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_choredefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('pending_approval', 'Pending approval'), ('completed', 'Completed'), ('missed', 'Missed')], default='available', max_length=20)),
                ('chore_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.choredefinition')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_chore_instances', to='chores.familymember')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chore_definition', 'date'), name='unique_chore_instance_per_definition_per_day')],
            },
        ),
    ]
