# Generated by Django 6.1.1 on 2026-09-15 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_choreinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.PositiveIntegerField()),
                ('chore_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.choreinstance')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.familymember')),
            ],
        ),
    ]
