# Generated by Django 6.1.1 on 2026-09-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('chore_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_records', to='chores.choredefinition')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_records', to='chores.familymember')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('family_member', 'chore_definition'), name='unique_streak_record_per_member_per_definition')],
            },
        ),
    ]
