# Generated by Django 6.1.1 on 2026-09-15 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_streakrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('point_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('streak_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='chores.household')),
            ],
        ),
    ]
